apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-static-pvc
  namespace: kube-system
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi