apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: {{ required "eMail is required for enabling letencrypt" .Values.ingress.tls.letsencrypt.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ .Values.app.name }}-cert
    solvers:
    - http01:
        ingress:
          class: traefik
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
    privateKeySecretRef:
      name: {{ .Values.app.name }}-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: le-crt
spec:
  secretName: tls-secret
  issuerRef:
    kind: Issuer
    name: letsencrypt
  {{- if not .Values.app.fqdn }}
  commonName: "{{ .Values.app.name }}.{{ .Values.app.domain }}"
  {{- else }}
  commonName: "{{ .Values.app.fqdn }}"
  {{- end }}