apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ampa.fullname" . }}-app
  labels:
    {{- include "ampa.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      {{- include "ampa.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "ampa.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: xls-data-ampa
          persistentVolumeClaim:
            claimName: nfs-ampa-pvc
        - name: static-ampa
          persistentVolumeClaim:
            claimName: nfs-static-pvc
      initContainers:
      - name: migrate
        image: "{{ .Values.images.ampa.repository }}:{{ .Values.images.ampa.tag | default .Chart.AppVersion }}"
        command: ['sh', '-c', 'python /code/manage.py migrate']
        env:
        {{- range $key, $val := .Values.app.env }}
          - name: {{ $key | upper }}
            value: {{ $val | quote }}
        {{- end }}
        resources:
          requests:
            memory: "50Mi"
            cpu: "250m"
          limits:
            memory: "200Mi"
            cpu: "500m"
      containers:
      - name: ampa
        image: "{{ .Values.images.ampa.repository }}:{{ .Values.images.ampa.tag | default .Chart.AppVersion }}"
        env:
        {{- range $key, $val := .Values.app.env }}
          - name: {{ $key | upper }}
            value: {{ $val | quote }}
        {{- end }}
          - name: "AMPA_APP_VERSION"
            value: "versió {{ default .Chart.AppVersion }}"
        resources:
          requests:
            memory: "50Mi"
            cpu: "250m"
          limits:
            memory: "200Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 8000
        volumeMounts:
          - mountPath: /code/xls
            name: xls-data-ampa
          - mountPath: /code/static
            name: static-ampa
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: http
            httpHeaders:
            - name: Host
              value: "{{ .Values.app.env.public_hostname }}"
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: http
            httpHeaders:
            - name: Host
              value: "{{ .Values.app.env.public_hostname }}"
          initialDelaySeconds: 30
          periodSeconds: 5