kind: Service
apiVersion: v1
metadata:
  name: {{ include "ampa.fullname" . }}
  labels:
    {{- include "ampa.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "ampa.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: 8000
    targetPort: 8000
