apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ampa.fullname" . }}-static
  labels:
    {{- include "ampa-static.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.static.replicaCount }}
  selector:
    matchLabels:
      {{- include "ampa-static.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ampa-static.selectorLabels" . | nindent 6 }}
    spec:
      volumes:
        - name: static-ampa
          persistentVolumeClaim:
            claimName: nfs-static-pvc
      containers:
      - name: ampa-static
        image: "{{ .Values.images.static.repository }}:{{ .Values.images.static.tag | default "alpine" }}"
        resources:
          requests:
            memory: "50Mi"
            cpu: "250m"
          limits:
            memory: "200Mi"
            cpu: "500m"
        ports:
          - name: http
            containerPort: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: static-ampa