kind: Service
apiVersion: v1
metadata:
  name: {{ include "ampa.fullname" . }}-static
  labels:
    {{- include "ampa-static.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "ampa-static.selectorLabels" . | nindent 6 }}
  ports:
  - name: http
    port: 80
    targetPort: 80
