{{ if .Values.ingress.enabled -}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "ampa.fullname" . }}-http
  labels:
    {{- include "ampa.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - host: ampa.systemadmin.es
    http:
      paths:
      - backend:
          serviceName: {{ include "ampa.fullname" . }}
          servicePort: 8000
  - host: static.ampa.systemadmin.es
    http:
      paths:
      - backend:
          serviceName: {{ include "ampa.fullname" . }}-static
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "ampa.fullname" . }}-https
  labels:
    {{- include "ampa.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt
    {{- with .Values.ingress.annotations }}
        {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  tls:
    - secretName: k3s-systemadmin
      hosts:
        - ampa.systemadmin.es
  rules:
  - host: ampa.systemadmin.es
    http:
      paths:
      - backend:
          serviceName: {{ include "ampa.fullname" . }}
          servicePort: 8000
{{ end -}}