{{ if .Values.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ampa.fullname" . }}-static
  labels:
    {{- include "ampa.labels" . | nindent 4 }}
  {{- with .Values.ingress.static_annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - secretName: k3s-systemadmin
      hosts:
        - {{ .Values.app.env.public_hostname }}
        - {{ .Values.app.env.static_hostname }}
  rules:
  - host: {{ .Values.app.env.static_hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "ampa.fullname" . }}-static
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ampa.fullname" . }}-web
  labels:
    {{- include "ampa.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt
    {{- with .Values.ingress.web_annotations }}
        {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  tls:
    - secretName: k3s-systemadmin
      hosts:
        - {{ .Values.app.env.public_hostname }}
        - {{ .Values.app.env.static_hostname }}
  rules:
  - host: {{ .Values.app.env.public_hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "ampa.fullname" . }}
            port:
              number: 8000
{{ end -}}