---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-http
  namespace: kube-system
spec:
  rules:
  - host: ampa.systemadmin.es
    http:
      paths:
      - backend:
          serviceName: ampa-32-svc
          servicePort: 8000
  - host: static.ampa.systemadmin.es
    http:
      paths:
      - backend:
          serviceName: ampa-static-10-svc
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-https
  namespace: kube-system
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - secretName: k3s-systemadmin
      hosts:
        - ampa.systemadmin.es
  rules:
  - host: ampa.systemadmin.es
    http:
      paths:
      - backend:
          serviceName: ampa-32-svc
          servicePort: 8000